services:
  - type: web
    name: profit-plus
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
